name: Lint

on:
  pull_request:
    branches: [main]
    paths:
      - "hello_world/**"
      - ".github/workflows/lint.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: hello_world/package-lock.json

      - name: Install dependencies
        working-directory: hello_world
        run: npm ci

      - name: Run Angular lint
        working-directory: hello_world
        run: npm run lint -- --max-warnings=0
